name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub registry
      uses: docker/login-action@v3
      with:
          #registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sfalda/sync_server:latest \
                  --tag sfalda/sync_server:v1.0.0 \
                  --tag sfalda/sync_server:stable
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_REGISTRY }}/rssfeedeater-server
